import js from "@eslint/js";
import globals from "globals";
import prettierConfig from "eslint-config-prettier";

export default [
    js.configs.recommended,
    prettierConfig,

    {
        ignores: [
            "**/node_modules/**",
            "**/lib/**",
            "**/dist/**",
            "**/build/**",
            "**/coverage/**",
            "**/*.min.js",
            "**/bower_components/**",
            "**/planet/libs/**"
        ]
    },

    {
        files: ["**/*.js", "**/*.mjs"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                ...globals.browser,
                ...globals.node,
                ...globals.jest,
                ...globals.jquery,

                Logo: "readonly",
                Blocks: "readonly",
                Turtles: "readonly",
                Activity: "readonly",
                _: "readonly",

                // Add all globals from activity.js /* global */ comment
                ALTO: "readonly",
                analyzeProject: "readonly",
                BASS: "readonly",
                BIGGERBUTTON: "readonly",
                BIGGERDISABLEBUTTON: "readonly",
                ActivityContext: "readonly",
                Boundary: "readonly",
                CARTESIAN: "readonly",
                changeImage: "readonly",
                closeWidgets: "readonly",
                COLLAPSEBLOCKSBUTTON: "readonly",
                COLLAPSEBUTTON: "readonly",
                createDefaultStack: "readonly",
                createHelpContent: "readonly",
                createjs: "readonly",
                DATAOBJS: "readonly",
                DEFAULTBLOCKSCALE: "readonly",
                DEFAULTDELAY: "readonly",
                define: "readonly",
                doBrowserCheck: "readonly",
                docByClass: "readonly",
                doSVG: "readonly",
                EMPTYHEAPERRORMSG: "readonly",
                EXPANDBUTTON: "readonly",
                FILLCOLORS: "readonly",
                getMacroExpansion: "readonly",
                getOctaveRatio: "readonly",
                getTemperament: "readonly",
                transcribeMidi: "readonly",
                GOHOMEBUTTON: "readonly",
                GOHOMEFADEDBUTTON: "readonly",
                GRAND: "readonly",
                HelpWidget: "readonly",
                HIDEBLOCKSFADEDBUTTON: "readonly",
                hideDOMLabel: "readonly",
                initBasicProtoBlocks: "readonly",
                initPalettes: "readonly",
                INLINECOLLAPSIBLES: "readonly",
                JSEditor: "readonly",
                LanguageBox: "readonly",
                ThemeBox: "readonly",
                MSGBLOCK: "readonly",
                NANERRORMSG: "readonly",
                NOACTIONERRORMSG: "readonly",
                NOBOXERRORMSG: "readonly",
                NOINPUTERRORMSG: "readonly",
                NOMICERRORMSG: "readonly",
                NOSQRTERRORMSG: "readonly",
                NOSTRINGERRORMSG: "readonly",
                PALETTEFILLCOLORS: "readonly",
                PALETTESTROKECOLORS: "readonly",
                PALETTEHIGHLIGHTCOLORS: "readonly",
                HIGHLIGHTSTROKECOLORS: "readonly",
                Palettes: "readonly",
                PasteBox: "readonly",
                PlanetInterface: "readonly",
                platform: "readonly",
                platformColor: "readonly",
                piemenuKey: "readonly",
                POLAR: "readonly",
                preparePluginExports: "readonly",
                processMacroData: "readonly",
                processPluginData: "readonly",
                processRawPluginData: "readonly",
                SaveInterface: "readonly",
                SHOWBLOCKSBUTTON: "readonly",
                SMALLERBUTTON: "readonly",
                SMALLERDISABLEBUTTON: "readonly",
                SOPRANO: "readonly",
                SPECIALINPUTS: "readonly",
                STANDARDBLOCKHEIGHT: "readonly",
                StatsWindow: "readonly",
                STROKECOLORS: "readonly",
                TENOR: "readonly",
                TITLESTRING: "readonly",
                Toolbar: "readonly",
                Trashcan: "readonly",
                TREBLE: "readonly",
                TURTLESVG: "readonly",
                updatePluginObj: "readonly",
                ZERODIVIDEERRORMSG: "readonly",
                GRAND_G: "readonly",
                GRAND_F: "readonly",
                SHARP: "readonly",
                FLAT: "readonly",
                buildScale: "readonly",
                TREBLE_F: "readonly",
                TREBLE_G: "readonly",
                GIFAnimator: "readonly",
                MUSICALMODES: "readonly",
                waitForReadiness: "readonly",
                body: "readonly",
                i18next: "readonly",
                wheelnav: "readonly",
                slicePath: "readonly",
                base64Encode: "readonly",
                disableHorizScrollIcon: "readonly",
                toFraction: "readonly",
                CARTESIANBUTTON: "readonly",
                piemenuGrid: "readonly",
                SELECTBUTTON: "readonly",
                CLEARBUTTON: "readonly",
                Midi: "readonly",
                ABCJS: "readonly",
                // Additional globals from other files
                EMPTYTRASHCONFIRMBUTTON: "readonly",
                COPYBUTTON: "readonly",
                EXTRACTBUTTON: "readonly",
                Tone: "readonly",
                A0: "readonly",
                TEMPERAMENTS: "readonly",
                INITIALTEMPERAMENTS: "readonly",
                TWELTHROOT2: "readonly",
                TWELVEHUNDRETHROOT2: "readonly",
                NATURAL: "readonly",
                SAMPLECENTERNO: "readonly",
                HELPCONTENT: "readonly",
                JSGenerate: "readonly",
                JS_API: "readonly",
                MusicBlocks: "readonly",
                acorn: "readonly",
                Oscilloscope: "readonly",
                ReflectionMatrix: "readonly",
                mixedNumber: "readonly",
                rationalToFraction: "readonly",
                toFixed2: "readonly",
                getTemperamentKeys: "readonly",
                timbreFilters: "readonly",
                instrumentsEffects: "readonly",
                DEFAULTOSCILLATORTYPE: "readonly",
                env: "readonly",
                TunerUtils: "readonly",
                TunerDisplay: "readonly",
                detectPitch: "readonly",
                pitchToNumber: "readonly",
                piemenuDissectNumber: "readonly",
                temperamentFloor: "readonly",
            }
        },

        rules: {
            "no-console": "off",
            "no-unused-vars": "off",
            "no-use-before-define": "off",
            "prefer-const": "off",

            "semi": ["error", "always"],
            "no-duplicate-case": "error",
            "no-irregular-whitespace": "warn"
        }
    },

    {
        files: ["**/*.mjs"],
        languageOptions: {
            sourceType: "module"
        }
    }
];
