blank_issues_enabled: false
contact_links:
  - name: 🙋🏾 🙋🏼‍ Question
    url: https://github.com/sugarlabs/musicblocks/discussions/new/choose
    about: Submit your question using GitHub Discussions.
