{
  "env": { "es6": true, "browser": true },
  "extends": ["eslint:recommended"],
  "rules": {
      "no-console": "warn",
      "no-mixed-spaces-and-tabs": "warn",
      "no-unused-vars": "warn",
      "no-use-before-define": "error",
      "prefer-const": [
        "warn",
        {
          "destructuring": "any",
          "ignoreReadBeforeAssign": true
        }
      ],
      "no-undef": "error",
      "no-unused-vars": "warn",
      "indent": ["warn", 4, { "SwitchCase": 1 }],
      "quotes": ["warn", "double", { "avoidEscape": true }],
      "semi": "error",
      "max-len":
        [
          "warn",
          {
            "code": 100,
            "ignoreTrailingComments": true,
            "ignoreComments": true,
            "ignoreStrings": true,
            "ignoreTemplateLiterals": true,
          },
        ],
      "no-trailing-spaces": ["warn", { "skipBlankLines": true, "ignoreComments": true }],
      "no-duplicate-case": "error",
      "no-irregular-whitespace": "warn",
    },
}
