name: "Automated Labeler"
on:
  pull_request:
    types: [opened, synchronize]  
  issues:
    types: [opened]               

jobs:
  label:
    runs-on: ubuntu-latest       

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  

    - name: Run Labeler
      uses: actions/labeler@v4    
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}