name: Run Jest Tests on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run Jest Tests
        run: npm test