name: Smoke Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          dockerfile: Dockerfile
          tags: smoke-test-image
          push: false

      - name: Run Docker container
        run: |
          docker run -d --name smoke-test-container -p 3000:3000 smoke-test-image
          sleep 10  # Wait for the server to start

      - name: Smoke test
        run: |
          timeout=30
          start_time=$(date +%s)
          while :
          do
              current_time=$(date +%s)
              if [[ $((current_time - start_time)) -gt $timeout ]]; then
                  echo "Smoke test timed out."
                  docker logs smoke-test-container
                  docker stop smoke-test-container
                  docker rm smoke-test-container
                  exit 1
              fi
              if curl --fail http://localhost:3000/; then
                  echo "Smoke test passed."
                  docker stop smoke-test-container
                  docker rm smoke-test-container
                  break
              else
                  echo "Waiting for server to start..."
                  sleep 1
              fi
          done